- name: Reconfigure GitLab
  ansible.builtin.command: gitlab-ctl reconfigure
  changed_when: true
  become: true

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: result
    verbosity: 2

- name: Check GitLab
  ansible.builtin.command: gitlab-rake gitlab:check
  changed_when: false
  become: true

- name: GitLab status
  ansible.builtin.command: gitlab-ctl status
  changed_when: false
  become: true
